version: "3.7"

services:
  db:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 1qazxsw2
    volumes:
      - db:/var/lib/mysql
    networks:
      - bridge-network

  redis:
    image: redis:5.0.3
    command: redis-server
    networks:
      - bridge-network

  webpacker:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /home/app/html
    environment:
      DB_POOL: 5
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: deployer
      DB_PASSWORD: 1qazxsw2
      DB_FOR_DEV: cp_db_dev
      DB_FOR_TEST: cp_db_test
      REDIS_HOST: redis://redis:6379/0
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      RACK_ENV: development
      NODE_ENV: development
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/home/app/html
      - backend_modules_cache:/home/app/html/node_modules
      - bundle_cache:/bundle
    ports:
      - "3035:3035"
    depends_on:
      - db
      - redis
    networks:
      - bridge-network

  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /home/app/html
    environment:
      DB_POOL: 5
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1qazxsw2
      DB_FOR_DEV: cp_db_dev
      DB_FOR_TEST: cp_db_test
      REDIS_HOST: redis://redis:6379/0
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      RACK_ENV: development
      NODE_ENV: development
      PLATFORM: sidekiq
      PORT: 3000
    command: /bin/sh "/home/app/html/config/runner/dev.sh"
    volumes:
      - .:/home/app/html
      - backend_modules_cache:/home/app/html/node_modules
      - bundle_cache:/bundle
    depends_on:
      - db
      - redis
      - webpacker
      - backend
    networks:
      - bridge-network

  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /home/app/html
    environment:
      DB_POOL: 5
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1qazxsw2
      DB_FOR_DEV: cp_db_dev
      DB_FOR_TEST: cp_db_test
      REDIS_HOST: redis://redis:6379/0
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      RACK_ENV: development
      NODE_ENV: development
      PLATFORM: backend
      PORT: 3000
    command: /bin/sh "/home/app/html/config/runner/dev.sh"
    volumes:
      - .:/home/app/html
      - backend_modules_cache:/home/app/html/node_modules
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - webpacker
    networks:
      - bridge-network

  frontend:
    tty: true
    stdin_open: true
    build:
      context: ./cpfrontend
      dockerfile: ./Dockerfile.dev
    working_dir: /home/app/html
    environment:
      PREFIX: ""
      SITE_NAME: "TooCooCats.com"
      SITE_DOMAIN: "127.0.0.1:8080"
      SITE_FEATURE_IMAGE: "https://toocoolcats.com/wp-content/uploads/2021/08/toocoolcats2.png"
      COUPON_PAGE_TITLE: "******** hotCoupons ********"
      COUPON_PAGE_DESCRIPTION: ""
      COUPON_API: "https://couponapi.toocoolcats.com/api/v1"
      BLOG_API: ""
    command: bash -c "yarn install && yarn dev"
    volumes:
      - ./cpfrontend:/home/app/html
      - frontend_build_cache:/home/app/html/build
      - frontend_modules_cache:/home/app/html/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - sidekiq
      - webpacker
      - backend
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  db:
  frontend_build_cache:
  frontend_modules_cache:
  backend_modules_cache:
  bundle_cache:
