FROM phusion/passenger-ruby26

ENV PORT=3000              \
    NODE_ENV=development   \
    RACK_ENV=development   \
    APP_DIR=/home/app/html \
    RAILS_ENV=development

RUN bash -lc "rvm reinstall 2.6.9 && rvm --default use ruby-2.6.9"
RUN mkdir -p $APP_DIR $APP_DIR/log $APP_DIR/tmp/pids

WORKDIR $APP_DIR

RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold"
RUN apt-get install mysql-client -y && apt-get install tzdata -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get update && apt-get install -y nodejs
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get update && apt-get install yarn

RUN apt-get install -y shared-mime-info

ADD Gemfile      $APP_DIR/Gemfile
ADD Gemfile.lock $APP_DIR/Gemfile.lock
RUN gem install bundler && bundle install

ADD package.json $APP_DIR/package.json
ADD yarn.lock    $APP_DIR/yarn.lock
RUN yarn install

COPY --chown=app:app . $APP_DIR

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#
EXPOSE $PORT

#
RUN chmod +x $APP_DIR/config/runner/dev.sh

#
CMD ["sh", "-c", "/home/app/html/config/runner/dev.sh"]
